steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['version']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA',
        '.',
      ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA',
      ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA',
        '--region',
        '${_REGION}',
        '--allow-unauthenticated',
        '--set-secrets=/secrets/sa/service_account.json=regnum-service-account-key:latest',
        '--set-env-vars=IMPERSONATED_USER_EMAIL=webminister@westkingdom.org,REDIRECT_URL=${_BASE_URL},BASE_URL=${_BASE_URL},REGNUM_API_URL=https://regnum-api-njxuammdla-uw.a.run.app,GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}',
        '--platform',
        'managed',
        '--port',
        '8080',
        '--timeout',
        '300s',
        '--memory',
        '512Mi',
        '--cpu',
        '1',
        '--min-instances',
        '1',
        '--max-instances',
        '10'
      ]

# Store the image name in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA'

# Define substitutions (variables)
substitutions:
  _REGION: 'us-west1'
  _ARTIFACT_REPO_NAME: 'regnum-artifacts'
  _SERVICE_NAME: 'regnum-front'
  _BASE_URL: 'https://regnum-front-85382560394.us-west1.run.app'
  _GOOGLE_CLIENT_ID: '' # Will be provided during build trigger
  _GOOGLE_CLIENT_SECRET: '' # Will be provided during build trigger

# Timeout for the entire build
timeout: '1800s'  # 30 minutes

# Add IAM permissions needed for the build
options:
  logging: CLOUD_LOGGING_ONLY