steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['version']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/regnum-front:$SHORT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/regnum-front:$SHORT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        'gcr.io/$PROJECT_ID/regnum-front:$SHORT_SHA',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
        '--port',
        '8501',
        '--allow-unauthenticated',
        '--memory',
        '1Gi',
        '--set-env-vars',
        'REGNUM_API_URL=https://regnum-api-njxuammdla-uw.a.run.app,BASE_URL=${_BASE_URL},STREAMLIT_ENV=production'
      ]

# Store the image name in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/regnum-front:$SHORT_SHA'

# Define substitutions (variables)
substitutions:
  _REGION: 'us-west1'
  _SERVICE_NAME: 'regnum-front'
  _BASE_URL: 'https://wkregnum-njxuammdla-uw.a.run.app'

# Timeout for the entire build
timeout: '1800s'  # 30 minutes

# Add IAM permissions needed for the build
options:
  logging: CLOUD_LOGGING_ONLY