steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['version']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/regnum/regnum-front:$BUILD_ID', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/regnum/regnum-front:$BUILD_ID']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        'us-west1-docker.pkg.dev/$PROJECT_ID/regnum/regnum-front:$BUILD_ID',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
        '--port',
        '8501',
        '--allow-unauthenticated',
        '--memory',
        '1Gi',
        '--set-env-vars',
        'REGNUM_API_URL=https://regnum-api-njxuammdla-uw.a.run.app,BASE_URL=${_BASE_URL},STREAMLIT_ENV=production,JWT_SECRET=your-jwt-secret-key-change-in-production,RECAPTCHA_SITE_KEY=your-recaptcha-site-key,RECAPTCHA_SECRET_KEY=your-recaptcha-secret-key,SMTP_SERVER=smtp.gmail.com,SMTP_PORT=465,SMTP_USERNAME=westkingdom@westkingdom.org,SMTP_PASSWORD=bjx1ueb7zat9yhk!CQB,SENDER_EMAIL=communications@westkingdom.org'
      ]

# Store the image name in Artifact Registry
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/regnum/regnum-front:$BUILD_ID'

# Define substitutions (variables)
substitutions:
  _REGION: 'us-west1'
  _SERVICE_NAME: 'regnum-front'
  _BASE_URL: 'https://wkregnum-njxuammdla-uw.a.run.app'

# Timeout for the entire build
timeout: '1800s'  # 30 minutes

# Add IAM permissions needed for the build
options:
  logging: CLOUD_LOGGING_ONLY