steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['version']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/regnum-front:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/regnum-front:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'regnum-front',
        '--image',
        'gcr.io/$PROJECT_ID/regnum-front:$COMMIT_SHA',
        '--region',
        'us-west1',
        '--platform',
        'managed',
        '--port',
        '8501',
        '--allow-unauthenticated',
        '--memory',
        '1Gi',
        '--set-env-vars',
        'REGNUM_API_URL=https://regnum-api-njxuammdla-uw.a.run.app,BASE_URL=https://wkregnum-njxuammdla-uw.a.run.app,REDIRECT_URL=https://wkregnum-njxuammdla-uw.a.run.app,REGNUM_ADMIN_GROUP=00kgcv8k1r9idky,BYPASS_AUTH=false,BYPASS_GROUP_CHECK=false,USE_MOCK_DATA=false,STREAMLIT_ENV=production',
        '--set-secrets',
        '/oauth/google_credentials.json=google-oauth-credentials:latest,/secrets/sa/service_account.json=regnum-service-account:latest'
      ]

# Store the image name in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/regnum-front:$COMMIT_SHA'

# Define substitutions (variables)
substitutions:
  _REGION: 'us-west1'
  _SERVICE_NAME: 'regnum-front'
  _BASE_URL: 'https://wkregnum-njxuammdla-uw.a.run.app'
  _REDIRECT_URL: 'https://wkregnum-njxuammdla-uw.a.run.app'
  _REGNUM_ADMIN_GROUP: '00kgcv8k1r9idky'

# Timeout for the entire build
timeout: '1800s'  # 30 minutes

# Add IAM permissions needed for the build
options:
  logging: CLOUD_LOGGING_ONLY