steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/regnum-front-redirect:latest',
        '-f',
        'redirect-dockerfile',
        '.',
      ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/regnum-front-redirect:latest',
      ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'regnum-front',
        '--image',
        '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/regnum-front-redirect:latest',
        '--region',
        '${_REGION}',
        '--allow-unauthenticated',
        '--platform',
        'managed',
        '--port',
        '8080',
        '--memory',
        '256Mi',
        '--cpu',
        '1',
        '--min-instances',
        '0',
        '--max-instances',
        '2'
      ]

# Store the image name in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO_NAME}/regnum-front-redirect:latest'

# Define substitutions (variables)
substitutions:
  _REGION: 'us-west1'
  _ARTIFACT_REPO_NAME: 'regnum-artifacts'

# Timeout for the entire build
timeout: '1800s'  # 30 minutes

# Add IAM permissions needed for the build
options:
  logging: CLOUD_LOGGING_ONLY 